imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:  ~
        cookie_lifetime: 0

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        server_version: 5.6 # hack for dbal 2.5 see https://github.com/doctrine/DoctrineBundle/issues/351
        charset:  UTF8

        mapping_types:
            duration: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    EyeOpenDictionaryBundle:
                        type: yml
                        dir: Resources/config/doctrine
                        prefix: EyeOpen\DictionaryBundle\Entity
                        is_bundle: true

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        env: %kernel.environment%
        frontier: %frontier_url%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ EyeOpenDictionaryAdminBundle ]
    filters:
        cssrewrite: ~

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
