parameters:
    database_driver:   pdo_mysql
    database_host:     33.33.33.13
    database_port:     ~
    database_name:     chore
    database_user:     chore
    database_password: chore

    locale: nl
    secret: mkpiouyturds5e4we6r7t8y9up9joihjkvcgfh

    frontier_url: https://www.eyeopen.nl

    admin_password: admin